version: "3.5"

services:
  php_fpm:
      build: .
      container_name: myoctober_php_fpm
      restart: always
      working_dir: /usr/share/nginx/myoctober
      networks:
          - myoctober
      volumes:
          - ./:/usr/share/nginx/myoctober
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
        image: nginx:1.18
        container_name: myoctober_nginx
        restart: always
        working_dir: /usr/share/nginx/myoctober
        networks:
            - myoctober
        ports:
            - "80:80"
        volumes:
            - ./:/usr/share/nginx/myoctober
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

networks:
  myoctober:
    driver: bridge
