version: "3.5"

services:
  php_fpm:
      build: .
      container_name: myoctober_php_fpm
      restart: always
      working_dir: /usr/share/nginx/myoctober
      networks:
          - myoctober
      volumes:
          - ./:/usr/share/nginx/myoctober
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
        image: nginx:1.18
        container_name: myoctober_nginx
        restart: always
        working_dir: /usr/share/nginx/myoctober
        networks:
            - myoctober
        ports:
            - "80:80"
        volumes:
            - ./:/usr/share/nginx/myoctober
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
      image: mysql:8.0
      container_name: myoctober_mysql
      restart: always
      working_dir: /usr/local/myoctober
      volumes:
          - ./:/usr/local/myoctober
          - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=1
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  myoctober:
    driver: bridge
